ERROR: [KEKWExeptionActivated(UBER)] ON: [   at TaxiBackApi.SystemControls.SystemControls.Uber.SystemProccesing(PackagedOrder InputPackagedOrder, ILogRepository iLogRepository, ILogger iLogger) in D:\DevOPS\TaxiBackApi\TaxiBackApi\SystemControls\SystemControls\Uber.cs:line 31] AT: [29.03.2021 11:26:02]
ERROR: [KEKWExeptionActivated(Test)] ON: [   at TaxiBackApi.Controllers.TakeAndSafeController.TestConnectionMetod() in D:\DevOPS\TaxiBackApi\TaxiBackApi\Controllers\TakeAndSafeController.cs:line 132] AT: [29.03.2021 11:57:22]
ERROR: [KEKWExeptionActivated(UBER)] ON: [   at TaxiBackApi.SystemControls.SystemControls.Uber.SystemProccesing(PackagedOrder InputPackagedOrder, ILogRepository iLogRepository, ILogger iLogger) in D:\DevOPS\TaxiBackApi\TaxiBackApi\SystemControls\SystemControls\Uber.cs:line 31] AT: [29.03.2021 11:57:30]
ERROR: [KEKWExeptionActivated(Test)] ON: [   at TaxiBackApi.Controllers.TakeAndSafeController.TestConnectionMetod() in D:\DevOPS\TaxiBackApi\TaxiBackApi\Controllers\TakeAndSafeController.cs:line 132] AT: [29.03.2021 11:57:30]
ERROR: [KEKWExeptionActivated(UBER)] ON: [   at TaxiBackApi.SystemControls.SystemControls.Uber.SystemProccesing(PackagedOrder InputPackagedOrder, ILogRepository iLogRepository, ILogger iLogger) in D:\DevOPS\TaxiBackApi\TaxiBackApi\SystemControls\SystemControls\Uber.cs:line 31] AT: [05.04.2021 21:28:02]
ERROR: [Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=13167; handshake=138; [Login] initialization=15; authentication=234; [Post-Login] complete=1162; ] ON: [   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at TaxiBackApi.Repositoryes.Orders.OrderRepository.GetRawOrder() in D:\DevOPS\TaxiBackApi\TaxiBackApi\Repositoryes\Orders\OrderRepository.cs:line 62
   at TaxiBackApi.Servises.DBaseOrderHandler.<DBHandlerStart>b__5_0(Object s, DoWorkEventArgs e) in D:\DevOPS\TaxiBackApi\TaxiBackApi\Servises\DBaseOrderHandler.cs:line 47] AT: [08.04.2021 19:24:06]
